[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@aragon/osx-commons-contracts/=lib/osx-commons/contracts/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@ensdomains/ens-contracts/=lib/ens-contracts/"
]

number_underscore="thousands"

optimizer = true
optimizer_runs = 200
via-ir = true
solc = "0.8.23"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
